### ISSUE TITLE
How to bind events from Firebase to calendar?

### ISSUE THREAD

**Issue by iamal12** [draganovik/day32-mobile#2]
How to bind the firebase events to this calendar? Can you please share that code? I can see you have binded Google events to the calendar. I tried binding the firebase events and was not successful.
Thanks

**Comment by draganovik** [comment]
Hi there @iamal12, Day32 is using [Firebase Database package](https://pub.dev/packages/firebase_database) to save event data from Google Calendar to the Firebase Database.

The structure of Google Event Object and Firebase Event Object are very simular (if not the same), but for integration with Syncfusion Calendar, Google Calendar Events are using adapter [event_data_source.dart](https://github.com/draganovik/Day32/blob/03a69038ce88c9bdcd4079c191d296afeab4936e/dev-flutter/lib/models/event_data_source.dart) so that Syncfusion Calendar can use them as a data source.

Looking back, with some minimal changes you should be able to replace `Provider.of<GoogleEventsProvider>(context);` with `Provider.of<FirebaseEventsProvider>(context);` , in [calendar_view.dart](https://github.com/draganovik/Day32/blob/03a69038ce88c9bdcd4079c191d296afeab4936e/dev-flutter/lib/views/calendar_view.dart).

Maybe there should be `firebase_event_data_source.dart` that adapts Firebase events for Syncfusion Calendar, but I think changing the provider will work just fine.

PS: Note that [firebase_options.dart](https://github.com/draganovik/Day32/blob/03a69038ce88c9bdcd4079c191d296afeab4936e/dev-flutter/lib/firebase_options.dart) is not using environment variables and that you should replace Firebase keys with your own as current variables are not valid anymore.

**Comment by iamal12** [comment]
Many thanks for your reply.
I changed the provider to the FirebaseProvider and then there was an error on the builder just below that.
return FutureBuilder(
        future: fep.loadEvents(),
The method loadEvents were not defined on firebase_event_data_source.dart

Please help me on how to define that method.

**Comment by draganovik** [comment]
@iamal12 I see, it should be fep.fetchAndSetEvents() instead of fep.loadEvents()

**Comment by draganovik** [comment]
As per my last comment, this issue should now be resolved, good luck!
